require:
    - rubocop-graphql
    - rubocop-performance
    - rubocop-rake
    - rubocop-rspec
    - rubocop-sequel

AllCops:
    Exclude:
        - 'tmp/*'
        - 'vendor/bundle/**/*'
    NewCops: enable
    TargetRubyVersion: 2.7.3

Layout/LineLength:
    Max: 90

Layout/SpaceAroundEqualsInParameterDefault:
    EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
    Exclude:
        - "spec/**/*"

Metrics/BlockLength:
    IgnoredMethods:
        - describe
        - context
        - it
        - RSpec.configure

Metrics/ClassLength:
    Max: 150

Metrics/MethodLength:
    Max: 15

RSpec/ContextWording:
    Prefixes:
        - and
        - with
        - without
        - when

Style/BlockDelimiters:
    EnforcedStyle: braces_for_chaining

Style/YodaCondition:
    EnforcedStyle: require_for_equality_operators_only
